"""add uuid in User table

Revision ID: dc3a885990e0
Revises: b88055a18c30
Create Date: 2022-12-16 15:09:10.909940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc3a885990e0"
down_revision = "b88055a18c30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
